### ISSUE TITLE
ENH: Support passing the HazelcastInstance ... via serverConfig.setServiceObject()

### ISSUE THREAD

**Issue by flqw** [ebean-orm/avaje-ebeanorm-hazelcast#2]
Is there a way to pass an existing HazelcastInstance to the Plugin or some workaround by initializing the Plugin myself? I have an existing instance in my application and think it's not the way to go to initialize multiple ones.

**Comment by rbygrave** [comment]
Currently there is not.

What could work is to pass a HazelcastInstance via ServerConfig get/setServiceObject().  So:

HazelcastInstance existingHazelcastInstance = ...
serverConfig.setServiceObject("hazelcast", existingHazelcastInstance);


---
In HzCacheFactory it uses get/setServiceObject() to read a hazelcastConfiguration ... and we could use the same mechanism to first check if a full HazelcastInstance was been supplied.
